defaults:
  - dataset: mosi          # Default dataset (can be overridden via CLI)

samples_order: [0,1,2]
weight_decay: 1e-4        # Default weight decay (can be overridden via Optuna)
fusion_layers: 2          # Default number of fusion layers (can be overridden via Optuna
mask_ratio: 0.0                # Default mask ratio (can be overridden via Optuna)
lambda_: 0.5                # Default lambda (can be overridden via Optuna)
scenario: clip_fusion  # Default scenario (can be overridden via CLI)
training:
  lr: 5e-5              # Learning rate for the optimizer
  batch_size: 128       # Batch size for training
  num_workers: 10       # Number of workers for data loading
  max_epochs: 30        # Maximum number of epochs for training

results_path: ${oc.env:HOME}/Projects/Personal/contrastive_fusion/contrastive_fusion/results/
